version: '2'
services:
  hbase:
    image: hbase1.0.0-cdh5.4.4:latest
    ports:
      - "2181:2181"
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030"
    networks:
      vpcbr:
          ipv4_address: 10.5.0.6

networks:
    vpcbr:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1